# theme.toml template for a Hugo theme
# See https://github.com/jetpax/hugoThemes#themetoml for an example

name = "SinglePaged"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Jekyll SinglePage theme ported to Hugo"
homepage = "http://siteforthistheme.com/"
tags = ["", ""]
features = ["", ""]
min_version = 0.1

[author]
  name = "Jonathan Peace"
  homepage = ""

# If porting an existing theme
[original]
  name = "SinglePaged"
  homepage = "http://jetpax.com/SinglePaged"
  repo = "https://github.com/jetpax/SinglePaged.git"
